codecov.yml
This PR will make github stop displaying codecov annotations inline in the code diffs.  Also it enables targets that were previously defined in coverage.yml, but were not in effect because they need to be in codecov.yml.
=> hide github annotations

requirements/constraints.txt
tox constrains this requirement to <2 but comes in later in the requirement file chain so this is required to resolve upgrade issues
=> constrain importlib_metadata

src/cc2olx/models.py, src/cc2olx/olx.py, tests/fixtures_data/imscc_file/discussion_topic.xml, tests/fixtures_data/imscc_file/discussion_topic_dependency.xml, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/studio_course_xml/course.xml, tests/test_models.py
This PR adds support for converting Common Cartridge [Discussion Topic Content Types](https://www.imsglobal.org/cc/ccv1p1/imscc_profilev1p1-Implementation.html#toc-43) to [OLX Discussion Component](https://edx.readthedocs.io/projects/edx-open-learning-xml/en/latest/components/discussion-components.html).
**JIRA tickets**: 
- https://tasks.opencraft.com/browse/BB-2894
~~**Discussions**:~~ 
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: None
1. Get ``imscc`` file which contains discussion topic
2. Convert using ``cc2olx``
3. Check if the output contains olx ``discussion`` component with contents from discussion topic
4. Check if the output contains ``HTML Block`` component with discussion description
5. Import generated output …
=> [BD-27] Add Discussion Topic Support

src/cc2olx/qti.py, tests/fixtures_data/imscc_file/resource_4_qti/assessment_qti.xml, tests/fixtures_data/studio_course_xml/course.xml
This PR adds support for converting Common Cartridge Multiple Response Type (``cc.multiple_response.v0p1``) to edX [Checkbox Problem](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/checkbox.html#checkbox-problem).  By default, it enables edX [partial creadit](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/checkbox.html#awarding-partial-credit-in-a-checkbox-problem) with ``EDC`` method.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3070
**Discussions**: https://openedx.slack.com/archives/C015PT4M8AY/p1600812218007200
~~**Screenshots**:~~ 
~~**Sandbox URL**:~~
**Merge deadline**: None
1. Get a common cartridge file with ``cc.multiple_response.v0p1`` …
=> [BD-27] Support Multiple Response Type

.coveragerc, src/cc2olx/filesystem.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/qti.py, src/cc2olx/utils.py
This PR adds some improvement in the ``cc2olx`` logging output. 
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3071
**Discussions**: https://openedx.slack.com/archives/C015PT4M8AY/p1600812119005700
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: "None" 
1. Find a Common Cartridge file that contains problem type that has not been implemented in ``cc2olx``.
2. Convert using ``cc2olx``.
3. Python ``logging`` module is used for log output instead of ``print`` statements.
4. Shows which file from ``imscc`` archive is currently being processed.
**Author notes and concerns**: N/A
**Reviewers**
~~**Settings**~~
=> [BD-27] Improve Logging and Output for cc2olx converter

src/cc2olx/filesystem.py
Parse the courses which have html in their description and it was throwing error. This error was mostly coming because of
unwanted &nbsp character which probably because the encoding of file is not `utf-8`.
**JIRA tickets**: [TNL-7655](https://openedx.atlassian.net/browse/TNL-7655)
~~**Screenshots**: ~~
~~**Sandbox URL**: TBD - sandbox is being provisioned (if needed).~~
Testing the course in problem:
1.  `cc2olx -i /path/to/<filename>.imscc`
This should not throw any errors and go through.
**Author notes and concerns**:
None
**Reviewers**
=> [BD-27] [TNL-7655] Added parser to handle different broken xml

src/cc2olx/olx.py, tests/fixtures_data/imscc_file/vertical.html, tests/fixtures_data/studio_course_xml/course.xml, tests/test_models.py
This PR helps to render the anchor tag which has href attribute instead of src.
**JIRA tickets**: [TNL-7963](https://openedx.atlassian.net/browse/TNL-7693)
**Screenshots**: None
**Sandbox URL**: None
1. cd cc2olx
1. pip install -e .
1. cd tests/fixtures_data/imscc_file
1. zip -r /path/to/<filename>.imscc *
1. cc2olx -i /path/to/<filename>.imscc 
In the CWD there will be an output folder created, there will be a "tar.gz", use that tar.gz file to import the course.
In the vertical section, there will be a link, click the link and the image should open in a new tab.
**Author notes and concerns**:
None
**Reviewers**
=> [BD-27] [TNL-7693][BB-3247]Fixed replacing of link from href attribute

requirements/base.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/quality.in, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, src/cc2olx/cli.py, src/cc2olx/filesystem.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/olx.py, src/cc2olx/qti.py, tests/test_cli.py, tests/test_models.py, tests/test_olx.py, tests/test_settings.py, tox.ini
This PR reformats all python code (with exception for OLX constructing code) using `black` tool, and enables formatting checking in Travis.
1. Add many blank lines somewhere in `setup.py`.
2. Run `tox`. It should fail.
**Reviewers**
=> Black formatting

src/cc2olx/filesystem.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/qti.py
Fixes warnings like:
```
FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
```
Also removes redundant logging of stacktrace and adds a few log statements.
=> Fix deprecation warnings, add log statements

src/cc2olx/iframe_link_parser.py, src/cc2olx/link_file_reader.py, src/cc2olx/olx.py, src/cc2olx/settings.py, src/cc2olx/tools/README.rst, tests/conftest.py, tests/test_cli.py, tests/test_kaltura_link_parser.py, tests/test_link_file_reader.py, tests/test_olx.py
I found that the tool that OpenCraft had written for converting embedded videos to video xblocks was expecting a "Youtube Id" column header.
Also ran `black` to reformat code so that travis formatting checks can pass.
=> Update README.rst and reformatted code

src/cc2olx/iframe_link_parser.py, src/cc2olx/tools/video_upload.py, tests/conftest.py, tests/fixtures_data/link_map_bad.csv, tests/fixtures_data/link_map_edx_only.csv, tests/fixtures_data/link_map_youtube_only.csv, tests/test_kaltura_link_parser.py
@edx/masters-devs-cosmonauts 
- Updated urls for video upload tool to point to prod as opposed to stage
- Allow user to only supply one of edX or Youtube Id in the video csv file provided. Previously this would raise an exception if a youtube ID was not provided, now it only raises an exception when neither the Youtube nor edX Id are present
=> Updates to video upload and converter tools

src/cc2olx/models.py, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/imscc_file/web_link_content.xml, tests/fixtures_data/studio_course_xml/course.xml, tests/test_models.py
This PR adds support for Common Cartridge v1.3 - for existing content types. 
- Web Content
- Associated Content
- QTI Assessment (CC Profiles)
- Discussion Topic
- Web Links
- LTI Link
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3575
**Discussions**: N/A
**Screenshots**:  N/A
**Sandbox URL**: N/A
**Merge deadline**: None
1. Pull this PR
2. Convert a Common Cartridge V1.3 file to OLX
3. It should convert existing content types correctly
**Author notes and concerns**:
1. A refactor might be better to add support for different CC versions.
**Reviewers**
=> [BD-27] [BB-3575] Existing Content Types - Common Cartridge v1.3 Support

src/cc2olx/models.py, tests/fixtures_data/imscc_file/course_settings/module_meta.xml, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/studio_course_xml/course.xml, tests/test_models.py
This PR fixes an issue related to empty sections while there are ``canvas`` items with content type ``ContextModuleSubHeader``. With this PR, ``cc2olx`` will treat these types of items as ``subsections`` and collapse related (consecutive) items under it as ``verticals``.
**JIRA tickets**: 
- https://tasks.opencraft.com/browse/BB-3539
- https://openedx.atlassian.net/browse/TNL-7891
~~**Discussions**:~~
~~**Screenshots**:~~
~~**Sandbox URL**:~~
**Merge deadline**: None
1. Pull this PR.
2. Find a canvas ``imscc`` file that contains ``ContextModuleSubHeader``, you can use the updated fixture with this PR.
3. Convert using ``cc2olx``. 
4. Check that item after ``ContextModuleSubHeader`` collapsed into it as verticals.
**Author notes and …
=> [BD-27][TNL-7891][BB-3539] Remove Empty Sections from cc2olx Conversions - ContextModuleSubHeader

src/cc2olx/qti.py, tests/fixtures_data/imscc_file/resource_4_qti/assessment_qti.xml, tests/fixtures_data/studio_course_xml/course.xml
This PR updates the method of parsing example solutions for Common Cartridge essay problems (cc.essay.v0p1) to be more specific as some Common Cartridge authoring software uses this field slightly differently.
It also adds basic response processing support for essay problems based around how Canvas generates example text for essay type problems. This fills in the ORA rubric's criterion fields with correct, incorrect, and general feedback fields to be referenced when performing assessments in the ORA review process.
**JIRA tickets**: Implements TNL-8016, BB-3863.
**Discussions**: Discussed in meetings and via email chains
**Merge deadline**: ASAP
1. Convert Common Cartridge using an essay type problem with example responses
2. Check that ORA …
=> Fix Essay Solution Parsing and Add Basic Essay Problem Response Processing

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
The automated upgrade task https://build.testeng.edx.org/job/cc2olx-upgrade-python-requirements/20/console failed due to a conflict with the constrained version of `importlib_metadata`. This constraint is no longer required, so removing it resolves the issue.
=> python requirements update

src/cc2olx/cli.py, src/cc2olx/external/canvas/__init__.py, src/cc2olx/external/canvas/module_meta.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/olx.py, src/cc2olx/settings.py, src/cc2olx/utils.py, tests/conftest.py, tests/fixtures_data/bad_passports.csv, tests/fixtures_data/imscc_file/course_settings/module_meta.xml, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/imscc_file/resource_external_lti_tool.xml, tests/fixtures_data/imscc_file/wiki_content/external_tool_retrieve.html, tests/fixtures_data/passports.csv, tests/fixtures_data/studio_course_xml/course.xml, tests/test_canvas_module_meta.py, tests/test_cli.py, tests/test_models.py, tests/test_olx.py, tests/test_passport_file_parser.py, tests/test_settings.py
Adds module meta parser and handler for external_tools
links for canvas flavoured CC. Also adds a parameter `----passport-file` to add LTI passports in `policy.json`
1. [TNL-8046](https://openedx.atlassian.net/browse/TNL-8046)
2. [BB-3973](https://tasks.opencraft.com/browse/BB-3973)
1. On master branch, Run cc2olx on a Canvas CC with external tools
2. Import the converted course in studio
3. Verify that the external tools content is converted to `MISSING CONTENT`
4. Checkout to this branch.
5. Convert the same Canvas CC course again.
6. Import the new converted course in studio
7. Verify that the external tools content is now visible. (LTI link might fail to load because of missing consumer key and secret)
1. Checkout to this branch
2. Convert a CC course with LTI components.
3. Verify …
=> [BD-27] [TNL-8046] Add module meta and handler for external_tools links

requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/quality.txt, requirements/test.txt, src/cc2olx/tools/video_download.py, tests/test_video_download_tool.py
This script searches for video links in CC courses, downloads them along with transcripts to a local directory and creates a link map csv file to be used with the cc2olx tool.
Pass a local .imscc file with Kaltura videos in it to the script and have it download the embedded videos.
The script shows the command line argument it requires.
=> [BD-27] Initial script for downloading videos

src/cc2olx/cli.py, src/cc2olx/settings.py, tests/test_cli.py
This allows specifying a different name for the output directory or zipfile which is now hardcoded to 'output'
It is helpful when trying the tool on various courses during development
=> [BD-27] Allow specifying output folder/zipfile name

src/cc2olx/olx.py, tests/fixtures_data/imscc_file/course_settings/module_meta.xml, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/imscc_file/resource_4_qti_no_items/assessment_meta.xml, tests/fixtures_data/imscc_file/resource_4_qti_no_items/assessment_qti.xml, tests/fixtures_data/studio_course_xml/course.xml, tests/test_models.py
Background: 
A course that was created by using the cc2olx tool was failing on import to Studio due to the following validation error: 
`1. ERROR InvalidPointer (course.xml): The <vertical display_name='xxx '> tag looks like it's trying to be a pointer but contains other attributes.`
The tags where the validation failed were childless verticals that also contained a `url_name` attribute - apparently this kind of tag without children should not contain any additional attributes.
The verticals that caused the validation errors should have had children with a qti content type (as observed in the .imscc file), however the assessments did not contain any problems. This caused any calls to `get_resource_content`, which is used to create the olx for the resource, to return the tuple ('qti', []), …
=> fix: if resource content is empty, replace with html

src/cc2olx/olx.py
The return value needs to be a list, otherwise an error is thrown.
Testing:
cc2olx -i test_data/ushistory.imscc
=> [BD-27] Return a list from _create_video_node.

src/cc2olx/qti.py
This PR makes "url_name" attribute of `<openassesment/>` unique. When there are a few such elements with the same value of this attribute — LMS shows multiple copies of the last one instead of showing different ORA blocks. 
**JIRA tickets**:
- [BB-3681](https://tasks.opencraft.com/browse/BB-3681)
- [TNL-7950](https://openedx.atlassian.net/browse/TNL-7950)
- [BLENDED-770](https://openedx.atlassian.net/browse/BLENDED-770)
TBA
**Author notes and concerns**:
1. Convert course, for which issue was reported.
2. Upload it to LMS.
3. Make sure that ORA blocks are different.
**Reviewers**
=> [BD-27] [TNL-7950] Make url_name of openassessment element unique

src/cc2olx/models.py
Files from the .imscc package should be read as utf-8 encoded. This was causing a bug for users trying to use the converter on windows (the system default encoding is Windows-1252).
=> fix: file should be read as utf-8 encoded

setup.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/tools/video_download.py, tests/conftest.py
All read and write operations for text files should be properly encoded using `utf-8` to avoid errors when running the tool on a PC.
=> fix: update file encoding for read and write operations

requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/quality.txt
zipp constraint was put in when we were on an old version of python, we can let it be free now which brings it to version 3.8.0 which is the general zipp version across edx.
=> remove now unnecessary zipp constraint

src/cc2olx/filesystem.py, src/cc2olx/models.py, src/cc2olx/utils.py, tests/fixtures_data/imscc_file/imsmanifest.xml, tests/fixtures_data/imscc_file/wiki_content/module-_-introduction.html, tests/test_models.py
Some courses in IMSCC format contain references to files with reserved characters in the filename. This causes the cc2olx tool to fail on operating systems for which those reserved characters are defined. 
We should rename those files and update references to them in our version of the IMS manifest tree. We do not need to modify the manifest file directly, as it is only used once to produce the tree structure.
=> feat: replace reserved characters in imscc filenames

requirements/pip-tools.txt
This commit upgrades the version of pip-tools used in this repository from 6.6.0 to 6.6.2.
In version 6.6.0 of pip-tools, there is a bug that is preventing pip-tools from working. This is breaking the Python requirements update GitHub action in this repository.
The error is ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars'. The error was reported in https://github.com/jazzband/pip-tools/issues/1617. The fix to this bug was released in version 6.6.2 of pip-tools. See the comment https://github.com/jazzband/pip-tools/issues/1617#issuecomment-1126245586.
=> fix: upgrade pip-tools to fix bug in version 6.6.0

src/cc2olx/olx.py, tests/fixtures_data/studio_course_xml/course.xml
We put in code specifically to make sure assessments each had their own url_name, but unfortunately that field is wiped out before it can actually take effect.
Fixes 15d4c023ce858ad7a5ed78718f382b7225b2a451 - notably the original code should have caused a test change but did not have one.
Tested by uploading a cc2olx converted from master and one converted with this code to stage. The master has the problem reported in https://2u-internal.atlassian.net/browse/CR-5011 - the Canvas Survey at the end of the course cannot be deleted. The updated import does not have the problem.
=> fix: actually use url_name set on assessments

src/cc2olx/olx.py
A canvas course with missing content in the discussion text section was causing the CC2OLX tool to break mid-conversion. Instead of erroring out, the tool should instead convert the content, and add a "MISSING CONTENT" message to the discussion node, as is done for other types of content that can't convert.
I have tested this change locally and can confirm that the tool now converts the course successfully.
=> fix: if discussion content is missing text, add missing content text

requirements/base.txt, requirements/ci.in, requirements/ci.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
Both requirements defined in ci.txt and quality.txt make use of `platformdirs`. Because both ci.txt and quality.txt are requirements in dev.txt, ci.txt and quality.txt must share the same versions of dependencies. 
My solution was to explicitly make quality.txt a requirement of ci.txt, which ensures that they share the same version of `platformdirs`.
=> fix: add ci requirements to ensure that dependency conflicts are avoided

src/cc2olx/constants.py, src/cc2olx/olx.py, src/cc2olx/utils.py, tests/conftest.py, tests/fixtures_data/html_files/cdata-containing-html.html, tests/fixtures_data/html_files/cleaned-cdata-containing-html.html, tests/fixtures_data/html_files/html-without-cdata.html, tests/fixtures_data/test_utils.py, tests/test_olx.py, tests/test_utils.py
During some OLX nodes creation (HTML, discussions) the entire content is wrapped into `CDATA` tag. But such content can already contain `CDATA` tags inside it, which causes errors. To fix it, the existed `CDATA` tag occurences are deleted (but its content is preserved) before such OLX nodes creation.
1. Update your Common Cartridge course `.imscc` dump (or use the attached one [cdata_bug_dump.imscc.zip](https://github.com/user-attachments/files/17737015/cdata_bug_dump.imscc.zip) but remove `.zip` extention leaving `.imscc`): add `CDATA` tag to any resource with `webcontent` type.
For example, let's assume your dump's `imsmanifest.xml` looks like
```xml
<manifest
xmlns="http://www.imsglobal.org/xsd/imsccv1p3/imscp_v1p1"
xmlns:lomr="http://ltsc.ieee.org/xsd/imsccv1p3/LOM/resource" …
```
=> fix: CDATA nesting into CDATA is avoided as it is prohibited

.dockerignore, Dockerfile, MANIFEST.in, README.rst, setup.py, utils.py
This PR is addressed to make the converter platform-independent.  
To perform it, Dockerfile is written, the files that should not be included into Docker image are specified in `.dockerignore`.  
All base requirements are installed during application installation.
1. Build the image:
```
docker build -t cc2olx .
```
2. Run the conversion command in a container by mounting passed argument path directories/files and passing the corresponding arguments to the script:
```
docker run --rm -v /input/file/path/cc_course_dump.imscc:/data/input/cc_course_dump.imscc -v /output/file/path/output_dir:/data/output/ cc2olx -r zip -i /data/input/cc_course_dump.imscc -o /data/output/edx_dump
```
It will convert Common Cartridge dump from */input/file/path/cc_course_dump.imscc* and save the OLX in …
=> feat: Application is dockerized

README.rst, pytest.ini, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/common_constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, src/cc2olx/cli.py, src/cc2olx/constants.py, src/cc2olx/dataclasses.py, src/cc2olx/django_settings.py, src/cc2olx/main.py, src/cc2olx/models.py, src/cc2olx/olx.py, src/cc2olx/settings.py, src/cc2olx/utils.py, src/cc2olx/validators/cli.py, tests/test_cli.py, tests/test_settings.py, tests/test_validators/test_cli.py
It is possible that the `.imscc` course dump contains files with relative links to resources for some reason not included into it (e.g. some static files of LMS that are not processed by its exporting tool). It can become a reason of broken images, not loaded styles etc.To handle such situations, it is allowed to specify the relative links source during converting.
Specify relative links source using `-s` flag:
```bash
cc2olx -i <IMSCC_FILE> -s <RELATIVE_LINKS_SOURCE>
```
FC-0063
"None"
=> feat: Source specifying for relative links is allowed

src/cc2olx/cli.py
There was an error that after specifying several input files, only the last one was processed. It's fixed and all input files are processed now.
1. Run the script with several `.imscc` input files:
```bash
cc2olx -i file1.imscc -i file2.imscc
```
2. Check `output` directory. It contain only `file2.imscc` processing outputs.
FC-0063
"None"
=> fix: [FC-0063] Multiple input files processing is fixed

README.rst, src/cc2olx/content_processors/__init__.py, src/cc2olx/content_processors/google_document.py, src/cc2olx/enums.py, src/cc2olx/settings.py, tests/conftest.py, tests/fixtures_data/imscc_files/main/imsmanifest.xml, tests/fixtures_data/imscc_files/main/weblinks/web_link_to_google_docs_home_page.xml, tests/fixtures_data/imscc_files/main/weblinks/web_link_to_google_document.xml, tests/fixtures_data/imscc_files/main/weblinks/web_link_to_google_drawings.xml, tests/fixtures_data/imscc_files/main/weblinks/web_link_to_google_presentation.xml, tests/fixtures_data/studio_course_xml/course.xml, tests/test_cli.py, tests/test_content_processors/test_google_document.py, tests/test_models.py
Originally, weblinks pointing to Google documents, spreadsheets, presentations, forms are displayed as an HTML OeX xblock.  
It is allowed to render such document inside the unit without the need to follow the link. The [xblock-google-drive](https://github.com/openedx/xblock-google-drive) xblock is used for this purpose. To use this feature, it's needed to pass the block name with `--content_types_with_custom_blocks` (or `-c`) CLI argument:
```
cc2olx -i cc_archive.imscc -c "google-document"
```
FC-0063
"None"
=> feat: Google document blocks processing is implemented
